# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel's Blog
email: daniel.maksymow@tuta.io
description:
  Setting goals is the first step in turning the invisible into the visible. ~ Tony Robbins.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  damaxi

source: ./
destination: ./_site

# Build settings
markdown: kramdown
exclude: ["README.md"]